### ISSUE TITLE
Improve prediction intervals

### ISSUE THREAD

**Issue by dirkschumacher** [reconhub/epichange#5]
`ciTools` is a good first start. But e.g. for neg. bin. regression, we could simply plugin the `mu/theta` into the quantile function of neg. bin. distribution instead having `ciTool` simulate something. Something similiar can be done for poisson regression.

**Comment by thibautjombart** [comment]
@dirkschumacher can we close this now?

**Comment by dirkschumacher** [comment]
For now yeah. Related to #13 as `brms` might make that obsolete.
